- shell: "findmnt -n -t nfs,nfs4 /mnt/data | grep infra"
  delegate_to: node1
  register: out
  failed_when: false
  changed_when: false
- set_fact:
    grade_results: "{{ grade_results + [ task_meta | combine({'check':'check_t07_nfs','passed': out.rc == 0}) ] }}"
