- shell: "systemctl is-enabled autofs && grep '^/homeauto' /etc/auto.master"
  delegate_to: node2
  register: out
  failed_when: false
  changed_when: false
- set_fact:
    grade_results: "{{ grade_results + [ task_meta | combine({'check':'check_t15_autofs','passed': out.rc == 0}) ] }}"
