- shell: "grep -E 'server\\s+infra.lab.example|pool\\s+infra.lab.example' /etc/chrony.conf"
  delegate_to: node2
  register: out
  failed_when: false
  changed_when: false
- set_fact:
    grade_results: "{{ grade_results + [ task_meta | combine({'check':'check_t10_chrony','passed': out.rc == 0}) ] }}"
