- shell: "grep -E 'baseurl=http://192.168.50.10/repo/(BaseOS|AppStream)' /etc/yum.repos.d/*.repo | wc -l"
  delegate_to: node1
  register: out
  failed_when: false
  changed_when: false
- set_fact:
    grade_results: "{{ grade_results + [ task_meta | combine({'check':'check_t02_repo','passed': (out.stdout | int) >= 2}) ] }}"
