- shell: "findmnt -n /data1 && lsblk -f | grep -E 'xfs' | grep -E 'vdb|data1'"
  delegate_to: node1
  register: out
  failed_when: false
  changed_when: false
- set_fact:
    grade_results: "{{ grade_results + [ task_meta | combine({'check':'check_t05_partition','passed': out.rc == 0}) ] }}"
