- shell: "test -f /home/analyst1/.ssh/authorized_keys"
  delegate_to: node1
  register: key
  failed_when: false
  changed_when: false
- set_fact:
    grade_results: "{{ grade_results + [ task_meta | combine({'check':'check_t12_ssh','passed': key.rc == 0}) ] }}"
