- shell: "firewall-cmd --list-services | grep -w ssh"
  delegate_to: node1
  register: out
  failed_when: false
  changed_when: false
- set_fact:
    grade_results: "{{ grade_results + [ task_meta | combine({'check':'check_t13_firewall','passed': out.rc == 0}) ] }}"
