- command: hostnamectl --static
  delegate_to: node1
  register: out
  failed_when: false
  changed_when: false
- set_fact:
    grade_results: "{{ grade_results + [ task_meta | combine({'check':'check_t01_hostname','passed': (out.stdout | trim) == 'node1.lab.example'}) ] }}"
