- shell: "systemctl is-enabled logarchive.timer && systemctl is-active logarchive.timer"
  delegate_to: node2
  register: out
  failed_when: false
  changed_when: false
- set_fact:
    grade_results: "{{ grade_results + [ task_meta | combine({'check':'check_t11_timer','passed': out.rc == 0}) ] }}"
